AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Globals:
  Function:
    MemorySize: 256
    Timeout: 30
    Runtime: nodejs20.x
    CodeUri: .
    Environment:
      Variables:
        TALK_AWS_REGION: !Sub ${AWS::Region}
        TALK_ENV_NAME: !Sub ${EnvironmentName}
        TALK_AWS_ACCOUNT_ID: !Sub ${AWS::AccountId}
        TALK_MONGO_PATH: !Sub ${MongoPath}
        TALK_COGNITO_USER_POOL_ID: !Sub ${CognitoUserPoolId}
        TALK_COGNITO_USER_POOL_CLIENT: !Sub ${CognitoUserPoolClient}
        TALK_STRIPE_SECRET_KEY: !Sub ${StripeSecretKey}
        TALK_SOURCE_BUCKET_NAME: !Sub ${SourceBucketName}
        TALK_SOURCE_UPLOAD_ACCESS_KEY: !Sub ${SourceUploadAccessKey}
        TALK_SOURCE_UPLOAD_SECRET_KEY: !Sub ${SourceUploadSecretKey}
        PINECONE_API_KEY: !Sub ${PineconeApiKey}
        PINECONE_INDEX: !Sub ${PineconeIndex}
        PINECONE_ENVIRONMENT: !Sub ${PineconeEnvironment}

Resources:
  # Handlers
  WebsocketHandler:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lib/handlers/websocket-handlers.handler
      FunctionName: !Sub 'talk-${EnvironmentName}-WebsocketHandler'
      Policies:
        - AmazonAPIGatewayInvokeFullAccess
        - AmazonAPIGatewayAdministrator
        
  PublicHandler:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lib/handlers/public-handlers.handler
      FunctionName: !Sub 'talk-${EnvironmentName}-PublicHandler'

  UserWorkspaceHandler:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lib/handlers/user-workspace-handlers.handler
      FunctionName: !Sub 'talk-${EnvironmentName}-UserWorkspaceHandler'

  KnowledgeHandler:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lib/handlers/knowledge-handlers.handler
      FunctionName: !Sub 'talk-${EnvironmentName}-KnowledgeHandler'

  SourceHandler:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lib/handlers/source-handlers.handler
      FunctionName: !Sub 'talk-${EnvironmentName}-SourceHandler'
        
  ChatHandler:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lib/handlers/chat-handlers.handler
      FunctionName: !Sub 'talk-${EnvironmentName}-ChatHandler'


  # Schedulled function to validate user billings
  # UserBillingValidationHandler:
  #   Type: 'AWS::Serverless::Function'
  #   Properties:
  #     Handler: lib/handlers/sys-configs-handlers/user-billing-validation-handler.handler
  #     FunctionName: !Sub 'talk-${EnvironmentName}-UserBillingValidationHandler'

  # UserBillingValidationEventRule: 
  #   Type: AWS::Events::Rule
  #   Properties: 
  #     State: "ENABLED"
  #     ScheduleExpression: "rate(1 hour)"
  #     Targets: 
  #       - 
  #         Arn: 
  #           Fn::GetAtt: 
  #             - "UserBillingValidationHandler"
  #             - "Arn"
  #         Id: "UserBillingValidationHandler"

  # PermissionUserBillingValidationHandler: 
  #   Type: AWS::Lambda::Permission
  #   Properties: 
  #     FunctionName: 
  #       Ref: "UserBillingValidationHandler"
  #     Action: "lambda:InvokeFunction"
  #     Principal: "events.amazonaws.com"
  #     SourceArn: 
  #       Fn::GetAtt: 
  #         - "UserBillingValidationEventRule"
  #         - "Arn"


Parameters:
  EnvironmentName:
    Type: String
  StageName:
    Type: String
  ApiGatewayName:
    Type: String
  MongoPath:
    Type: String
  CognitoUserPoolId:
    Type: String
  CognitoUserPoolClient:
    Type: String
  StripeSecretKey:
    Type: String
  SourceBucketName:
    Type: String
  SourceUploadAccessKey:
    Type: String
  SourceUploadSecretKey:
    Type: String
  PineconeApiKey:
    Type: String
  PineconeIndex:
    Type: String
  PineconeEnvironment:
    Type: String