AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  RestApiTemplate:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./template-rest-api.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        StageName: !Ref StageName
        ApiGatewayName: !Ref ApiGatewayName
        DomainName: !Ref DomainName
        DomainCertificateArn: !Ref DomainCertificateArn
        CognitoUserPoolArn: !Sub arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${CognitoUserPoolId}
        UserWorkspaceHandlerArn: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:talk-${EnvironmentName}-UserWorkspaceHandler
        KnowledgeHandlerArn: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:talk-${EnvironmentName}-KnowledgeHandler
        SourceHandlerArn: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:talk-${EnvironmentName}-SourceHandler
        ChatHandlerArn: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:talk-${EnvironmentName}-ChatHandler
        PublicHandlerArn: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:talk-${EnvironmentName}-PublicHandler

  WebsocketApiTemplate:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./template-ws-api.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        StageName: !Ref StageName
        ApiGatewayName: !Ref ApiGatewayName
        WebsocketHandlerArn: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:talk-${EnvironmentName}-WebsocketHandler

Parameters:
  EnvironmentName:
    Type: String
  StageName:
    Type: String
  ApiGatewayName:
    Type: String
  CognitoUserPoolId:
    Type: String
  DomainName:
    Type: String
  DomainCertificateArn:
    Type: String