AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  # WS API
  WSApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub '${ApiGatewayName}-ws'
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.action"

  # Stage
  WSApiDeploymentStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: !Ref StageName
      AutoDeploy: true
      DeploymentId:  !Ref WSApiDeployment
      ApiId: !Ref WSApi

  # Deployment
  WSApiDeployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
      - ConnectRoute
      - MainRoute
      - DisconnectRoute
    Properties:
      ApiId: !Ref WSApi

  # Routes
  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WSApi
      RouteKey: $connect
      AuthorizationType: NONE
      OperationName: ConnectRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref ConnectInteg
  ConnectInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WSApi
      Description: Connect Integration
      IntegrationType: AWS_PROXY
      IntegrationUri: 
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebsocketHandlerArn}/invocations
  
  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WSApi
      RouteKey: $disconnect
      AuthorizationType: NONE
      OperationName: DisconnectRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref DisconnectInteg
  DisconnectInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WSApi
      Description: Disconnect Integration
      IntegrationType: AWS_PROXY
      IntegrationUri: 
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebsocketHandlerArn}/invocations
  
  MainRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WSApi
      RouteKey: main
      AuthorizationType: NONE
      OperationName: MainRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref MainInteg
  MainInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WSApi
      Description: Man Integration
      IntegrationType: AWS_PROXY
      IntegrationUri: 
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebsocketHandlerArn}/invocations          

  # Permissions
  WebsocketHandlerPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref WebsocketHandlerArn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*

Outputs:
  WebSocketApi:
    Value: !Ref WSApi

Parameters:
  EnvironmentName:
    Type: String
  StageName:
    Type: String
  ApiGatewayName:
    Type: String
  WebsocketHandlerArn:
    Type: String